language: python

matrix:
  include:
    - sudo: required
      services:
        - docker
      env: PIP=pip
           CIBW_BUILD='*-manylinux1_x86_64'
           CIBW_SKIP='cp34-*'
           CIBW_TEST_REQUIRES='pytest'
           CIBW_TEST_COMMAND='python -m pytest {project}/tests'
    - sudo: required
      services:
        - docker
      env: PIP=pip
           CIBW_BUILD='*-manylinux1_i686'
           CIBW_SKIP='cp34-*'
           CIBW_TEST_REQUIRES='pytest'
           CIBW_TEST_COMMAND='python -m pytest {project}/tests'
    - os: osx
      language: generic
      env: PIP=pip2
           CIBW_BUILD='cp27-* cp35-*'
    - os: osx
      language: generic
      env: PIP=pip2
           CIBW_BUILD='cp36-* cp37-*'

env:
  global:
    - CIBW_BEFORE_BUILD='pip install "numpy>=1.7" && pip install "pandas>=0.20"'
    - CIBW_TEST_REQUIRES='pytest codecov'
    - CIBW_TEST_COMMAND='coverage run --source=monetdblite -m pytest {project}/tests && codecov'
    - TWINE_USERNAME=kutsurak
      # test-pypi (kutsurak)
    - secure: "f8bDgNpnuZp+SN/ByBtABRLpopWM3/5uR1GrRne8M0JvOM18t7F1xsxZHuAfqIBSeZGPaOJkRfBYZE2jOl1YO9ZYEXzK1QJ5CbRAdd4cAvBbf0uexe5LFimXpMSeicXYoulY32IJi6ZYgxPWwFEwUGBKhQ/lZbaOp36XEka4WFnHk+5fGjuFYyGtnVYxQ36CuNE4Y1ivZZPOzbryrEsHSZm8d9pWkY9hgA50Z824N79pZBvsN8lbwW1jgvo5VeBWlZ/VumZNTeEoHkW5i+MK56u3Wi1LANgKy8wp+0Rwf4dGyLg+tS5XZgAW+Z/2jlVKtAwyjIRjIWiwa2rboUiUAQPv9Nw/VHh48AWP1FDAKcL5LEhLOUSuobjgFI1klwzZYVftOap6lMQIqFA1QvaEO11A7ZyRWdmUKXXaWiPdeo54miDPq4LyDOqsCO3keZ9RTWKiayn/D4Z0nZQ+MudbSL7/orbd7CKhbKVJEvmpgm4d/zsxjdhzXBWSQ4XtSXp51fBLYMKbRB+F6yTYeYk9QnaId8fPyKcfC7xrTNn9y0oHInhex0Pqh1gE/NUhEFdo5fYw/Tx+JfpbZ8adgj1vA+QfurybfUM75rwweAnDao26nIQrLgInSWwuSX/n9D62nMDbLZucCGfjDgk3bVcWhE6IFjbo1JIcC90F7Y5fDwo="

script:
  - $PIP install cibuildwheel==0.10.1
  - cibuildwheel --output-dir wheelhouse
  - |
    if [[ $TRAVIS_TAG ]]; then
      $PIP install twine
      python -m twine upload --repository-url https://test.pypi.org/legacy/ --skip-existing wheelhouse/*.whl
    fi
