language: python

matrix:
  # include:
  #   - sudo: required
  #     services:
  #       - docker
  #     env: PIP=pip
  #          CIBW_BUILD='*-manylinux1_x86_64'
  #          CIBW_SKIP='cp34-*'
  #   - sudo: required
  #     services:
  #       - docker
  #     env: PIP=pip
  #          CIBW_BUILD='*-manylinux1_i686'
  #          CIBW_SKIP='cp34-*'
  #   - os: osx
  #     language: generic
  #     env: PIP=pip2
  #          CIBW_BUILD='cp27-* cp35-*'
  #   - os: osx
  #     language: generic
  #     env: PIP=pip2
  #          CIBW_BUILD='cp36-* cp37-*'
  include:
    - sudo: required
      python: 3.6
      services:
        - docker
      env: PIP=pip
           CIBW_BUILD='cp36-manylinux1_x86_64'
      after_success:
        - $PIP install numpy>=1.17 pandas>=0.20.0
        - $PIP install --no-index -f wheelhouse/ monetdblite
        - $PIP install pytest codecov
        - cd $HOME
        - coverage run --source=monetdblite -m pytest $HOME/$TRAVIS_REPO_SLUG/tests
        - codecov

    - os: osx
      language: generic
      env: PIP=pip2
           CIBW_BUILD='cp37-*'

env:
  global:
    - CIBW_BEFORE_BUILD='pip install -r requirements.txt'
    - CIBW_TEST_REQUIRES='pytest'
    - CIBW_TEST_COMMAND='pytest {project}/tests'

script:
  - $PIP install cibuildwheel==0.10.0
  - cibuildwheel --output-dir wheelhouse


  
