language: python

matrix:
  # include:
  #   - sudo: required
  #     services:
  #       - docker
  #     env: PIP=pip
  #          CIBW_BUILD='*-manylinux1_x86_64'
  #          CIBW_SKIP='cp34-*'
  #   - sudo: required
  #     services:
  #       - docker
  #     env: PIP=pip
  #          CIBW_BUILD='*-manylinux1_i686'
  #          CIBW_SKIP='cp34-*'
  #   - os: osx
  #     language: generic
  #     env: PIP=pip2
  #          CIBW_BUILD='cp27-* cp35-*'
  #   - os: osx
  #     language: generic
  #     env: PIP=pip2
  #          CIBW_BUILD='cp36-* cp37-*'
  include:
    - sudo: required
      services:
        - docker
      env: PIP=pip2
           CIBW_BUILD='cp37-manylinux1_x86_64'
    - os: osx
      language: generic
      env: PIP=pip2
           CIBW_BUILD='cp37-*'

env:
  global:
    - CIBW_BEFORE_BUILD='pip install -r requirements.txt'
    - CIBW_TEST_REQUIRES='pytest codecov'
    - CIBW_TEST_COMMAND='coverage run --source=monetdblite -m pytest {project}/tests && codecov --commit=$TRAVIS_COMMIT'
    - secure: "nNglg/v/L6KLgLd+j0kF0Fa+rJ8uAFdXanniMCfDeSjEV8ndIy1wKg57coL1/+0hTTIH0VrWcvsTxW+v/i5KIcdHsp65sYcQ/bEzFD2wcJTvyYt0zqSS+45bHVE/4bCsjpNTctFqlsrfDbYz6ozG1uF1PQGYJ6RyeDt4ySXFyyW19Xik0kbx4J8lFZINaqdfkfzAWfNm8qkLQIDkH+8X6xgt/3r/SG7ttd9qB0AEltE+aZGCdeMRVj92FHJrvOY1EaEg0jqsPbL9UnFfGwynRM+R7Mkb3hqhAJVYkUDp97BpG8VbUdSZqBnESxkfjQhk0Us0XO+iaeTDmeXYuf0LNJt6JCHGTL6oNS4qNi/sTzqG3a3ll2ESu7J93Nd+HYRMqR7IH1B18ETkrhmrOPpUD/dNtt5j2trDdqhYlFg84Ra82wk1i7y4HmX2mBDrjLLU/lWB2c1t4wOcdObu/3E6x6eiU4PA7pxwlKRHvDbnC9U9SE54MWrIAiVw5PtgZ9s6irLnegvvtCQaf69gxZhlxoZWaHBinjv451fB0jFjoV9l5nj7wiWaXSHc7ROv2wkCJaG/mbOxKmF72p5FR9fGxuzebNseWpWRlghYIgThR4KMJ0OOI25Zcz9F3UWuPNabfFQD6RxhvO7fbu8sbs8VU6LWJI7neFxT12KrvtRmOok="

script:
  - $PIP install cibuildwheel==0.10.0
  - cibuildwheel --output-dir wheelhouse
