language: python

matrix:
  # include:
  #   - sudo: required
  #     services:
  #       - docker
  #     env: PIP=pip
  #          CIBW_BUILD='*-manylinux1_x86_64'
  #          CIBW_SKIP='cp34-*'
  #   - sudo: required
  #     services:
  #       - docker
  #     env: PIP=pip
  #          CIBW_BUILD='*-manylinux1_i686'
  #          CIBW_SKIP='cp34-*'
  #   - os: osx
  #     language: generic
  #     env: PIP=pip2
  #          CIBW_BUILD='cp27-* cp35-*'
  #   - os: osx
  #     language: generic
  #     env: PIP=pip2
  #          CIBW_BUILD='cp36-* cp37-*'
  include:
    - sudo: required
      python: 3.6
      services:
        - docker
      env: PIP=pip
           CIBW_BUILD='cp36-manylinux1_x86_64'
           CIBW_TEST_REQUIRES='pytest codecov'
           CIBW_TEST_COMMAND='coverage run --source=monetdblite -m pytest {project}/tests && cp .coverage /host/tmp'
      after_success:
        - $PIP install codecov
        - cp /tmp/.coverage .
        - codecov

    - os: osx
      language: generic
      env: PIP=pip2
           CIBW_BUILD='cp37-*'

env:
  global:
    - CIBW_BEFORE_BUILD='pip install -r requirements.txt'
    - CIBW_TEST_REQUIRES='pytest codecov'
    - CIBW_TEST_COMMAND='coverage run --source=monetdblite -m pytest {project}/tests'

script:
  - $PIP install cibuildwheel==0.10.0
  - cibuildwheel --output-dir wheelhouse


  
