language: python

matrix:
  include:
    - sudo: required
      services:
        - docker
      env: PIP=pip
           CIBW_BUILD='*-manylinux1_x86_64'
           CIBW_SKIP='cp34-*'
           CIBW_TEST_REQUIRES='pytest'
           CIBW_TEST_COMMAND='python -m pytest {project}/tests'
    - sudo: required
      services:
        - docker
      env: PIP=pip
           CIBW_BUILD='*-manylinux1_i686'
           CIBW_SKIP='cp34-*'
           CIBW_TEST_REQUIRES='pytest'
           CIBW_TEST_COMMAND='python -m pytest {project}/tests'
    - os: osx
      language: generic
      env: PIP=pip2
           CIBW_BUILD='cp27-* cp35-*'
    - os: osx
      language: generic
      env: PIP=pip2
           CIBW_BUILD='cp36-* cp37-*'

env:
  global:
    - CIBW_BEFORE_BUILD='pip install -r requirements.txt'
    - CIBW_TEST_REQUIRES='pytest codecov'
    - CIBW_TEST_COMMAND='coverage run --source=monetdblite -m pytest {project}/tests && codecov'

script:
  - $PIP install cibuildwheel==0.10.0
  - cibuildwheel --output-dir wheelhouse
