language: python
python: 3.6
sudo: required

env:
  global:
    # COVERALLS_TOKEN=<the actual token>



matrix:
  include:
    - sudo: required
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64
      secure: "NRN0tkcbNVKJhWmD1poC5nO5iNevl44BRyX7m07S6jjZB/FN5Wu8V6GFonMAaS3j9+yKAYn9a4pnLj6XuOw29OKjK00jAm3xg7LL0ZfViy+YXfzCzXrdTsG9pKTjNq8LIODQNH+mng0pr4Z/ptPSrAgjiJllotQSgTS8PTTSKr1rVQnaOa4nNAOHHrrfsanjJIjkU0FlYWEdOiuj2/wh7f9j2TdbsYby25xyQmg4EUO/WoiN/+sijNWsPDjxLWxn1zBYscZnlRKCL2hcrKCukTdp5/T7S1FrUn2/UZR+MCupu1F0TJTaIMk8bfR9VHeBgEH0Mvg4lQJfzM2U3C1soLi0P2k5gtiQ4VHLef+8nVoNB21JnOpzXtyBTYHb1MVie6/cze32uMoscC0uHpZTNtmT0ZTIG7ZLOTl1v1MxYTtoWfWTRKs38lV36B+WhQMLvR6SjanwXnCZjEfpNele+jQP1OqleYOBqjcdl32kMxtemx95ngsaIu9Bz5iEmNFyNghUOJSMV0bAwHb6s5BGnvIwzpYxR7V0CxbMKVyJJT3hFD+KtnyaEBKTwDnpN7/3rDDH95DN+wmaP3KyFboxr6AowhBBHW9oKiVY3izTMFrdYp1T0iICwqxLDSRl+001D+YWtOoeeH4hw1Tk8GbfsQr++qh2Z34KX3C/plZIz/4="

      # secure: "jsC4Ysy9wHouTUOT7t6ixNqwGF+QkuYj6bAAgeodd7LChj0q347s43vHdPVyJZoslNlELTCiEQwf4fZ9wheU7YOem5/yT8U0NoQIrAajtH7fvwP2XaLk+G1BjnbCyhOWwVcdyAfQ54RH5FNDPgdYuW3a+htWTTsfYuKt4KqIKilylur3JjmLd2bou5uvds5zwGLdIBKaGIezkZeKQ3hBsz7XjglcMuvGU60vdTr2RV4NA8URhUgAe9Vj9qkrdWDs3QkDYUeOqxUc4IjU/IB4hbxf1v5bdnLQTfd1d1WoHSKbq+uhIrdO/2KIQN7jwM5+DOnOYKxVCnK8h9WcJDSi6HIWcoxetSkDRfKNHcMDn2La/kCD+promXUbPyYRPZIPw/+9kZqbNB+1pD5BsO9fsFQU8jaw6zE+I4B2AaaAdQA6NADIh+inmMNcXwcyuVEXt3sU3GFB+GjODfxjYlXyUi5qO+1Q2xvVV0/F6rN9ZkxyHZ5Ltyaswv/vzLF9SvvJB8/0Kc2UpwHFV10cT5Gjgq2N/RJufoy34+MdV4umUev5px0rQW5THDe3IhiRYGkst1pvQKaarLNB13vYlxB3lxaOgLYWqe+J18j3IRNOryCfqARLl1c+17i5BVETyzZCPtS29Tl4LxB6qKRG4EMTcByha9xK74pDP0HZJd5lfbA="
    - sudo: required
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux1_i686
           PRE_CMD=linux32

install:
  - docker pull $DOCKER_IMAGE

script:
  - docker run --rm -e COVERALLS_REPO_TOKEN=$COVERALLS_TOKEN -v `pwd`:/io $DOCKER_IMAGE $PRE_CMD /io/travis/build_wheels.sh

before_deploy:
  - sudo chown -R $USER dist/
  - sudo chown -R $USER lib/
  - sudo chown -R $USER tests/

deploy:
  skip_cleanup: true
  provider: pypi
  server: https://test.pypi.org/legacy/
  user: kutsurak
  skip_existing: true
  on:
    # pypi.org
    tags: true
    # test.pypi.org
    # branch: master
  password:
    # test.pypi.org
    # secure: "GRjtbiq6mgqaej6N/eVmpWHs+Um4aeGhp8+rnK03q9X5Ho7TsFZKjg56d45564GBcpdEdXdUnjfe61UzqQlSN0YhLafUHMiyUHz7SX+v4N0vzFUfXpoisnCT+WlYwWC8dOP2O/kvnS4elxOOB9BGRlxPxV5cxW1wUBRvg8NJBbucuxS5bi30lCwcnaN+hYOMsT+5iSNrAR8CHhL3Qm/OULBRYSR0TzI6Vi0Spm6tbvdq7eNZHL8nVRek+y9sivyVBzAMJze87veaCjj6eTycQzyo0vVRnZG+0RCIQQWllUbF19DiDfdu0AdQYzAYjUBUdNKVTSf6ws/9kBUY7iDROe5OwiI02batAq1+8hTa/xxj7R9scf9ctIf255GH4SMdQDukqbn6xIHKRVRQrfOyNI3SBTPAWz1Mmx5WzZpmWS7hySyBw5Uv1rg53mHWXZmClkxvhDGJVQ4JVxsTK4sP4pTxcf534IOWN7ljyerUJKh9xujuGpw5CR2Q52AOhOkMqNEDTvWNjj1f34BhgUVQhqbUWvhGveQBnZ9mkXaHUO8Lud1doNOuzspSosr1ZB1o75ioh7NX7fGDjUvIZXGLNzJdenmb0VXv6e45gHdJku8L5thiy2Wd51qWQdTD03tDfAQ2f2QEEtWbRimKC6DmrqlOKCPnR+SJjW26c6cNNDs="
    # pypi.org
    secure: "hH9vjphvoNESP5S74lWFphti9m4jxnFpzvgfpa8bxD3Eqc+9IkeeFg1wbjc3qZ4p31q1rPf0E/R417w1TFY5tvj3SaCQABdcC9WGW4aUAsNGC5TXwEbozKzqPbSvdAiuAawnb877jyRmEx3mOtANyI83Agyp8DbHIfki6ViDIlsfm5lu4sdKQNzhmhWmVg3kcW2iV/xCpHopNRbc4XVC5Sae/CYy2JLUItgmeibLic4wJyiRZoJtmjhHqi3UGDSx49ugyY4BEn7B4CA/Endyd8w3Exy8Izxo6Zk/V2SM+VvOVF4PLjRkjzlJ1VjP2Byrmt8RLgaLxmQghb2DEfLoB8zs7XCP1XNtJNieZMRfB0Jl7pbP9j8sWcXppKEITT2eLb4agDf6cqZt7NWEVilOVOFQx2SbcK4EgqlubDQ8e/hWm+gVxBB/WzTSGhs/Eaz/lqjARt8x2nUmy9mWO/HVYiQJ6w2DVS+4Q4FM6Ccjao6M2mfc3I1MaeAN/1ctGEs0lt2mLMsiEQadBMa0ojwvHMwW4J+ytuP9zA6+xyzVAtjuaYCPPPytMbfG1kOCRpNoKwossJ8oaRn3ST3DgZ07vGjFj0bHu4gKIsorJgLWYATURCG2gsI4kwoO9pDT9PWad5FPBfPIEDTD6ZajTuQ5uAraUFCINa7yFt+oMXcamxQ="
