language: python
python: 3.6
sudo: required

env:
  global:
    # COVERALLS_TOKEN=<the actual token>
    # test.pypi.org
    secure: "GFbZn6aVVF+8KgsMStcv8+sJb3o3AtAetwCaUmu30M2M1MOUO7wRlbuJb+n8qvoi4tKlUwucGQeYoobrFGBNLgibbuF/aB7PWDibOvsOf44o2ZP7AjD6GynxcCgIHIBddsxkdU49SGUc6pbrIN+3KLibb9tNAG+mcoZpuxbl+BcgxyHZc6UzgUnAfibThH+qu01m6Dz4WluY/wayb0VDCKz4AdQN/6zjN/P3OdvGGOnXf9ku3AsyKy/3uN1z+5PQnhgTgBF5eW2nJeOSl0qnRiOeWDaeG47YVI3HD4ZKWm2Sa1MR8PSfNFBXGOHtuV7wdhv77dwJVB03ZELInXpU2oNbPEEYmQgsR1kNijyiEgx71snVcRJChOQrNMmJ/QF5Kk39tAmwBXH6eMI0elDTZLATiDy+rIM72wNyU+VpbOOlq/6PMRljEFV9ETeKziF17xifHYL1PCbG8fq/teuVhP8V/E5C3MuF4N2sMUeYjm0Gk1AHCbprvRsIoMUMssj0cYpqBWCY2C1g/kPLX061pIATZyD5r8UY6/OL6W8b460LSJk8SvawPBq/tJb8NWE8aodtJroCp+OpNNCR8lwgHw9Q4XyMMpeaAKBNiTey5j75X4NC4z6j8biRsR4P77WTA1rF/VyNWAU7RVnOUwYgj97HYa3xNt4jZUcV91dqIg0="
    # pypi.org
    # secure: "mxIICYKvUKsl/k/mxaih7kZGpux4pF2MmHOC7g2M2diVMzv9bisKbTVCPfO5AB+0K6DOZgefw6QBFWsTilu+01O6h5nnlKjBEbCYkQ69ZCz78xf1Q1vEBxFO44IZpj25QNz6hmWIyvyvdEYq0zSnMsGUOF5PcTyZJDVEXtrqgzpXrCcifbMR0PNR1Qso5sS04SFrxBKKur6XFJsgIbY4QpRD3P7/fGn3fgJEaIu9hWXcDdKBxSVUpRVdBtkAeWK0n4R5V5DCDueypNc67kDrD+X+yj34uKNfGM0p37CszwYOp98WJGaNOKGXnPP7Kyb/10QWmkeOHEzE/EsaUDNQCYjeVfL5IS7hljaCIVHvLJaIbgbcdMwdmqMzBW/rF3AWFoH/Q1QLNk/oU7dtpBgslteIUQpa/4Fh6wXLNTnwNjtIyAgVkAvlA+ha5GrKgeqlSsN6aLCb+aqex62lXetLSsyFtlBKhQ8mmrFq/h19R/QSvAEcCINUPo8i11MKAFRu+mC6eJAqSnYDsgWW6FQcnnE4cq+337piV0NgMHOVqlNrxAghdoEM322Hb385xraD9IkY7Kah8ENggjfdGn3dJAvs4gsDnBQVjtqVfmH6pug3r3jaCgGZvj8MNWYhiYG+2eZcxfc+hZl1+aXfy9tBrlFNaRlP45CrXj7i32HImOo="



matrix:
  include:
    - sudo: required
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64
    - sudo: required
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux1_i686
           PRE_CMD=linux32

install:
  - docker pull $DOCKER_IMAGE

script:
  - docker run --rm -e COVERALLS_REPO_TOKEN=$COVERALLS_TOKEN -v `pwd`:/io $DOCKER_IMAGE $PRE_CMD /io/travis/build_wheels.sh

before_deploy:
  - sudo chown -R $USER dist/
  - sudo chown -R $USER lib/
  - sudo chown -R $USER tests/

deploy:
  skip_cleanup: true
  provider: pypi
  server: https://test.pypi.org/legacy/
  user: kutsurak
  skip_existing: true
  on:
    # pypi.org
    tags: true
    # test.pypi.org
    # branch: master
  password:
    # test.pypi.org
    # secure: "GRjtbiq6mgqaej6N/eVmpWHs+Um4aeGhp8+rnK03q9X5Ho7TsFZKjg56d45564GBcpdEdXdUnjfe61UzqQlSN0YhLafUHMiyUHz7SX+v4N0vzFUfXpoisnCT+WlYwWC8dOP2O/kvnS4elxOOB9BGRlxPxV5cxW1wUBRvg8NJBbucuxS5bi30lCwcnaN+hYOMsT+5iSNrAR8CHhL3Qm/OULBRYSR0TzI6Vi0Spm6tbvdq7eNZHL8nVRek+y9sivyVBzAMJze87veaCjj6eTycQzyo0vVRnZG+0RCIQQWllUbF19DiDfdu0AdQYzAYjUBUdNKVTSf6ws/9kBUY7iDROe5OwiI02batAq1+8hTa/xxj7R9scf9ctIf255GH4SMdQDukqbn6xIHKRVRQrfOyNI3SBTPAWz1Mmx5WzZpmWS7hySyBw5Uv1rg53mHWXZmClkxvhDGJVQ4JVxsTK4sP4pTxcf534IOWN7ljyerUJKh9xujuGpw5CR2Q52AOhOkMqNEDTvWNjj1f34BhgUVQhqbUWvhGveQBnZ9mkXaHUO8Lud1doNOuzspSosr1ZB1o75ioh7NX7fGDjUvIZXGLNzJdenmb0VXv6e45gHdJku8L5thiy2Wd51qWQdTD03tDfAQ2f2QEEtWbRimKC6DmrqlOKCPnR+SJjW26c6cNNDs="
    # pypi.org
    secure: "hH9vjphvoNESP5S74lWFphti9m4jxnFpzvgfpa8bxD3Eqc+9IkeeFg1wbjc3qZ4p31q1rPf0E/R417w1TFY5tvj3SaCQABdcC9WGW4aUAsNGC5TXwEbozKzqPbSvdAiuAawnb877jyRmEx3mOtANyI83Agyp8DbHIfki6ViDIlsfm5lu4sdKQNzhmhWmVg3kcW2iV/xCpHopNRbc4XVC5Sae/CYy2JLUItgmeibLic4wJyiRZoJtmjhHqi3UGDSx49ugyY4BEn7B4CA/Endyd8w3Exy8Izxo6Zk/V2SM+VvOVF4PLjRkjzlJ1VjP2Byrmt8RLgaLxmQghb2DEfLoB8zs7XCP1XNtJNieZMRfB0Jl7pbP9j8sWcXppKEITT2eLb4agDf6cqZt7NWEVilOVOFQx2SbcK4EgqlubDQ8e/hWm+gVxBB/WzTSGhs/Eaz/lqjARt8x2nUmy9mWO/HVYiQJ6w2DVS+4Q4FM6Ccjao6M2mfc3I1MaeAN/1ctGEs0lt2mLMsiEQadBMa0ojwvHMwW4J+ytuP9zA6+xyzVAtjuaYCPPPytMbfG1kOCRpNoKwossJ8oaRn3ST3DgZ07vGjFj0bHu4gKIsorJgLWYATURCG2gsI4kwoO9pDT9PWad5FPBfPIEDTD6ZajTuQ5uAraUFCINa7yFt+oMXcamxQ="
