language: python

matrix:
  include:
    - sudo: required
      services:
        - docker
      env: PIP=pip
           CIBW_BUILD='cp35-* cp36-* cp37-* cp38-*'
           CIBW_SKIP='*-manylinux1_i686'
           CIBW_TEST_REQUIRES='pytest'
           CIBW_TEST_COMMAND='python -m pytest {project}/tests'
    - os: osx
      language: generic
      env: PIP=pip2
           CIBW_BUILD='cp35-* cp36-* cp37-* cp38-*'

env:
  global:
    - CIBW_BEFORE_BUILD='pip install "numpy>=1.7" && pip install "pandas>=0.20"'
    - CIBW_TEST_REQUIRES='pytest codecov'
    - CIBW_TEST_COMMAND='coverage run --source=monetdblite -m pytest {project}/tests && codecov'
    - TWINE_USERNAME=kutsurak
    # test-pypi (kutsurak)
    # - secure: "f8bDgNpnuZp+SN/ByBtABRLpopWM3/5uR1GrRne8M0JvOM18t7F1xsxZHuAfqIBSeZGPaOJkRfBYZE2jOl1YO9ZYEXzK1QJ5CbRAdd4cAvBbf0uexe5LFimXpMSeicXYoulY32IJi6ZYgxPWwFEwUGBKhQ/lZbaOp36XEka4WFnHk+5fGjuFYyGtnVYxQ36CuNE4Y1ivZZPOzbryrEsHSZm8d9pWkY9hgA50Z824N79pZBvsN8lbwW1jgvo5VeBWlZ/VumZNTeEoHkW5i+MK56u3Wi1LANgKy8wp+0Rwf4dGyLg+tS5XZgAW+Z/2jlVKtAwyjIRjIWiwa2rboUiUAQPv9Nw/VHh48AWP1FDAKcL5LEhLOUSuobjgFI1klwzZYVftOap6lMQIqFA1QvaEO11A7ZyRWdmUKXXaWiPdeo54miDPq4LyDOqsCO3keZ9RTWKiayn/D4Z0nZQ+MudbSL7/orbd7CKhbKVJEvmpgm4d/zsxjdhzXBWSQ4XtSXp51fBLYMKbRB+F6yTYeYk9QnaId8fPyKcfC7xrTNn9y0oHInhex0Pqh1gE/NUhEFdo5fYw/Tx+JfpbZ8adgj1vA+QfurybfUM75rwweAnDao26nIQrLgInSWwuSX/n9D62nMDbLZucCGfjDgk3bVcWhE6IFjbo1JIcC90F7Y5fDwo="
    # pypi (kutsurak)
    - secure: "JeI84LgwppnCEV2qslRHow4dEsU3r5pS/cvIrIA863XPoT8bUFPAYuf0NcMAwRr/6MLw5r5dFBtAviB7OBncvKvqNpbpDsEt72i6vlbZNk06xnCSjAiPRvBqF2N6NJURCTSa2gV//enkkoGMVA2zOLOWMMyN6DYSUUk2mR5d46cVzrdkDS8AD35ycH8aYyxqS/Kv/Vp1RX2osxZCa02D/gEH3C5WE2TYk+yKC7LTXgUKpswhLaJV0lcBI1D9RLwYSzVKBuzQNL6hHwUT8MCk1W6Ivl1aFYL5YZoXSH915TAuaeel5Sy/C+QDH7VwgqlAjjNINmRrG7hEGtHfKmDh3zraJeQ3tJpDetk8IfnzBPnslWri0vZZRvyZrG9Xm014oHW+ZvbhRo9Tf6cMIoExAt/d5LCVJaA6OKMe/Or39RIbWZBPuWyUxWiZsO9ypcak7y5FLHakVUnOjcdv7gTCnGyiTgy7Z1E48czesa9dl5fZP5CaRahq2o4IuXXsOykN/SFiDsIns6IpA3Rnu3TmKGFlO+NgpayKu+ji+oClFGDqj7daTjvyT3vwyq6vre1D4jCYM+5edMT6UjLgOuOUZRczJSMnI7Y8GWjWIfuuGQZ+B4oJrOphdAqVuasSIgjP6BToZYmyMwjQWoQ3FnOH9bhp0mDJDFVfSbJFkp98oZk="
script:
  - $PIP install cibuildwheel==1.4.1
  - cibuildwheel --output-dir wheelhouse
  - |
    if [[ $TRAVIS_TAG ]]; then
      $PIP install twine
      python -m twine upload --skip-existing wheelhouse/*.whl
    fi
