environment:
  CIBW_TEST_REQUIRES: "pytest pytest-cov"
  CIBW_TEST_COMMAND: "pytest --cov=monetdblite {project}\\tests"
  CIBW_BEFORE_BUILD: "pip install -r {project}\\requirements.txt"
  CIBW_SKIP: "cp27-* cp34-* *-win32"
  TWINE_USERNAME: kutsurak

  # To securely? change the password twine uses to upload wheels at
  # PyPI register an account at appveyor and go to #
  # https://ci.appveyor.com/tools/encrypt Enter the password in the
  # form there, encrypt it and copy-paste the encrypted value below.

  TWINE_PASSWORD:
    # test.pypi.org (kutsurak)
    # secure: FI99drs2RsYAJqo198nJT/D6RhTMYFncW5Ccn7h6o2M=

    # pypi (kutsurak)
    secure: TwnBmDB0PDYXEE6bNN+0JWDEJEL8X0euJe8Pk12zWO4=

install:
  # Make sure we are using a recent Python 3
  - set PATH=C:\Python37;%PATH%
  - cmd: python -m pip install cibuildwheel==0.10.1
  - cmd: python -m pip install numpy

build_script:
  - cmd: python -m cibuildwheel --output-dir wheelhouse
  - ps: >-
      if ($env:APPVEYOR_REPO_TAG -eq "true") {
        python -m pip install twine
        python -m twine upload --repository-url https://test.pypi.org/legacy/ --skip-existing wheelhouse\*
      }

artifacts:
  - path: "wheelhouse\\*.whl"
    name: Wheels
