environment:
  CIBW_TEST_REQUIRES: "pytest pytest-cov"
  CIBW_TEST_COMMAND: "pytest --cov=monetdblite {project}\\tests"
  CIBW_BEFORE_BUILD: "pip install -r {project}\\requirements.txt"
  CIBW_SKIP: "cp27-* cp34-* *-win32"
  TWINE_USERNAME: kutsurak
  TWINE_PASSWORD:
    secure: J1D0IVMyIRXPyZYlhSNt26ZwNdP2zQ3cVUqzhMGHX1s=

install:
  # Make sure we are using a recent Python 3
  - set PATH=C:\Python37;%PATH%
  - cmd: python -m pip install cibuildwheel==0.10.1
  - cmd: python -m pip install numpy

build_script:
  - cmd: python -m cibuildwheel --output-dir wheelhouse
  - ps: >-
      if ($env:APPVEYOR_REPO_TAG -eq "true") {
        python -m pip install twine
        twine upload --skip-existing wheelhouse\*
      }

artifacts:
  - path: "wheelhouse\\*.whl"
    name: Wheels
