environment:

  matrix:
    - PYTHON_VERSION: 2.7
      PYPATH: "C:\\Python27"
    - PYTHON_VERSION: 3.5
      PYPATH: "C:\\Python35"
    - PYTHON_VERSION: 3.6
      PYPATH: "C:\\Python36"

image: Visual Studio 2015

platform:
  - x86
  - x64

init:
  - ps: if ($Env:PLATFORM -eq "x64") {$Env:PYPATH = "${Env:PYPATH}-x64"}
  - ps: Write-Host $Env:PYPATH

install:
  - "%PYPATH%\\python.exe -m pip install wheel"
  - "%PYPATH%\\python.exe -m pip install pytest"
  - "%PYPATH%\\python.exe -m pip install numpy"
  # Make sure the compiler is accessible
  - '"%VS140COMNTOOLS%\..\..\VC\vcvarsall.bat" %PLATFORM%'

test_script:
  - "%PYPATH%\\python.exe -m pytest"

build_script:
  - "%PYPATH%\\python.exe setup.py install"


after_test:
  - "%PYPATH%\\python.exe setup.py bdist_wheel"

artifacts:
  - path: dist\*

#on_success:
#  You can use this step to upload your artifacts to a public website.
#  See Appveyor's documentation for more details. Or you can simply
#  access your wheels from the Appveyor "artifacts" tab for your build.
